### ISSUE TITLE
Use for RDFS ontologies

### ISSUE THREAD

**Issue by kvistgaard** [oeg-upm/OWLChangeOntology#5]
To be able to use this for RDFS ontologies, some changes are needed.
For example, there should be a superclass between `och:PropertyChange` and its current subclass for changes of properties declared only as `rdf:Property`.

**Comment by DiegoCondeHerreros** [comment]
The ontology has undergone many changes, in it's current release it represents OWL ontology changes, since OWL is an extension of RDFS then it already covers RDFS ontologies.
